// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vfvtbltkthzezivccwiw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZmdnRibHRrdGh6ZXppdmNjd2l3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwNTc2MDgsImV4cCI6MjA1OTYzMzYwOH0.kkVxZBFCE_oMg82xqSvDm3hM-vIeZM9-ubPZE7gpiIU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);